language: python

matrix:
  include:
    - os: linux
      env:
        - INSTALL_LUA="lua=5.3"
        - LUA="lua"
    - os: osx
      env:
        - INSTALL_LUA="lua=5.3"
        - LUA="lua"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - pip install hererocks
  - hererocks lua_install -rlatest --$INSTALL_LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH
  - wget http://www.lua.org/ftp/lua-5.3.4.tar.gz
  - tar zxvf lua-5.3.4.tar.gz
  - cd lua-5.3.4; make $TRAVIS_OS_NAME MYCFLAGS=-fPIC; cd ..

install:
  - luarocks install busted
  - luarocks install luacov
#  - luarocks install luacov-coveralls
  - luarocks make # This installs necessary runtime dependencies

script:
  - busted -c -o gtest -v spec/

#after_success:
  - luacov "titan%-compiler" "/spec/[^/]+.lua" "titanc" && bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: change

cache:
  directories:
    - $HOME/.luarocks
